package ru.kosterror.testsforge.filestorageservice.exception;

public class InternalException extends RuntimeException {

    public InternalException(String message, Throwable cause) {
        super(message, cause);
    }

}
